#include "ktool_i.h"

/* generated by fbt from .png files in images folder */
#include <ktool_icons.h>

#include <furi_hal_resources.h>

/* Reads the VS-sense divider and publishes the result for the GUI thread.
 * Runs on the app thread: the ADC conversion is blocking and must not touch the GUI thread. */
static void ktool_sample_vs(KTool* ktool) {
    /* Convert outside the lock - only the publish step needs to be mutually exclusive. */
    uint16_t raw = furi_hal_adc_read(ktool->adc, KTOOL_ADC_CHANNEL);
    float pin_mv = furi_hal_adc_convert_to_voltage(ktool->adc, raw);
    uint32_t vs_mv = (uint32_t)(pin_mv * KTOOL_VS_DIVIDER_GAIN + KTOOL_VS_OFFSET_MV);

    furi_mutex_acquire(ktool->mutex, FuriWaitForever);
    ktool->adc_raw = raw;
    ktool->vs_mv = vs_mv;
    furi_mutex_release(ktool->mutex);
}

static void ktool_draw_callback(Canvas* canvas, void* context) {
    KTool* ktool = context;

    /* Take a snapshot and get out - never hold the lock while drawing. */
    furi_mutex_acquire(ktool->mutex, FuriWaitForever);
    uint16_t adc_raw = ktool->adc_raw;
    uint32_t vs_mv = ktool->vs_mv;
    furi_mutex_release(ktool->mutex);

    uint32_t bplus_mv = vs_mv + (uint32_t)KTOOL_D1_DROP_MV;

    canvas_clear(canvas);

    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 0, 10, "KTool");

    char buf[24];
    canvas_set_font(canvas, FontSecondary);

    /* No %f: newlib-nano float formatting is not something to rely on here. */
    snprintf(
        buf,
        sizeof(buf),
        "VS   %lu.%02lu V",
        (unsigned long)(vs_mv / 1000),
        (unsigned long)((vs_mv % 1000) / 10));
    canvas_draw_str(canvas, 0, 26, buf);

    snprintf(
        buf,
        sizeof(buf),
        "B+   %lu.%02lu V",
        (unsigned long)(bplus_mv / 1000),
        (unsigned long)((bplus_mv % 1000) / 10));
    canvas_draw_str(canvas, 0, 38, buf);

    snprintf(buf, sizeof(buf), "raw  %u", adc_raw);
    canvas_draw_str(canvas, 0, 50, buf);
}

static void ktool_input_callback(InputEvent* event, void* context) {
    KTool* ktool = context;

    KToolEvent ktool_event = {
        .type = KToolEventTypeInput,
        .input = *event,
    };

    /* GUI thread: the queue has spare capacity, so this does not block in practice. */
    furi_message_queue_put(ktool->event_queue, &ktool_event, FuriWaitForever);
}

static void ktool_timer_callback(void* context) {
    KTool* ktool = context;

    KToolEvent ktool_event = {.type = KToolEventTypeTick};

    /* Timer service thread: never block here. A dropped tick only costs one frame. */
    furi_message_queue_put(ktool->event_queue, &ktool_event, 0);
}

static KTool* ktool_alloc(void) {
    KTool* ktool = malloc(sizeof(KTool));

    ktool->event_queue = furi_message_queue_alloc(8, sizeof(KToolEvent));
    ktool->mutex = furi_mutex_alloc(FuriMutexTypeNormal);

    ktool->adc_raw = 0;
    ktool->vs_mv = 0;

    /* PC3 must be analog before the ADC can sample it. */
    furi_hal_gpio_init(&gpio_ext_pc3, GpioModeAnalog, GpioPullNo, GpioSpeedLow);

    ktool->adc = furi_hal_adc_acquire();
    /* Long sampling time is mandatory here: the divider looks like 150k||10k ~ 9.4k
     * to the ADC, and a short window would leave the sample-and-hold cap undercharged. */
    furi_hal_adc_configure_ex(
        ktool->adc,
        FuriHalAdcScale2500,
        FuriHalAdcClockSync64,
        FuriHalAdcOversample64,
        FuriHalAdcSamplingtime247_5);

    ktool->gui = furi_record_open(RECORD_GUI);
    ktool->view_port = view_port_alloc();
    view_port_draw_callback_set(ktool->view_port, ktool_draw_callback, ktool);
    view_port_input_callback_set(ktool->view_port, ktool_input_callback, ktool);

    ktool->timer = furi_timer_alloc(ktool_timer_callback, FuriTimerTypePeriodic, ktool);

    /* Last: from here on the view port is live and callbacks may fire. */
    gui_add_view_port(ktool->gui, ktool->view_port, GuiLayerFullscreen);

    FURI_LOG_I(TAG, "started, ADC on PC3 (channel 4)");

    return ktool;
}

static void ktool_run(KTool* ktool) {
    /* One reading up front so the first frame is not blank. */
    ktool_sample_vs(ktool);

    furi_timer_start(ktool->timer, furi_ms_to_ticks(KTOOL_TICK_PERIOD_MS));

    KToolEvent event;
    while(furi_message_queue_get(ktool->event_queue, &event, FuriWaitForever) == FuriStatusOk) {
        if(event.type == KToolEventTypeInput) {
            if(event.input.type == InputTypeShort && event.input.key == InputKeyBack) break;
        } else if(event.type == KToolEventTypeTick) {
            ktool_sample_vs(ktool);
            view_port_update(ktool->view_port);
        }
    }

    furi_timer_stop(ktool->timer);
}

static void ktool_free(KTool* ktool) {
    if(!ktool) return;

    /* Silence both event producers before freeing what they write to. */
    gui_remove_view_port(ktool->gui, ktool->view_port);
    furi_timer_free(ktool->timer);

    view_port_free(ktool->view_port);
    furi_message_queue_free(ktool->event_queue);
    furi_record_close(RECORD_GUI);

    furi_hal_adc_release(ktool->adc);
    furi_mutex_free(ktool->mutex);

    free(ktool);
}

int32_t ktool_app(void* p) {
    UNUSED(p);

    KTool* ktool = ktool_alloc();

    ktool_run(ktool);

    ktool_free(ktool);

    return 0;
}
