#include "ktool_i.h"

/* generated by fbt from .png files in images folder */
#include <ktool_icons.h>

#include <furi_hal_adc.h>
#include <furi_hal_resources.h>

static void ktool_draw_callback(Canvas* canvas, void* context) {
    UNUSED(context);

    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 0, 10, "KTool");
}

static void ktool_input_callback(InputEvent* event, void* context) {
    furi_message_queue_put((FuriMessageQueue*)context, event, FuriWaitForever);
}

static KTool* ktool_alloc(void) {
    KTool* ktool = malloc(sizeof(KTool));

    ktool->gui = furi_record_open(RECORD_GUI);
    ktool->view_port = view_port_alloc();
    view_port_draw_callback_set(ktool->view_port, ktool_draw_callback, NULL);
    gui_add_view_port(ktool->gui, ktool->view_port, GuiLayerFullscreen);

    ktool->input_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    view_port_input_callback_set(ktool->view_port, ktool_input_callback, ktool->input_queue);

    return ktool;
}

static void ktool_run(KTool* ktool) {
    InputEvent event;
    while(furi_message_queue_get(ktool->input_queue, &event, FuriWaitForever) == FuriStatusOk) {
        if(event.type == InputTypeShort && event.key == InputKeyBack) break;
    }
}

static void ktool_free(KTool* ktool) {
    if(!ktool) return;

    gui_remove_view_port(ktool->gui, ktool->view_port);
    view_port_free(ktool->view_port);
    furi_message_queue_free(ktool->input_queue);
    furi_record_close(RECORD_GUI);
    free(ktool);
}

int32_t ktool_app(void* p) {
    UNUSED(p);

    KTool* ktool = ktool_alloc();

    ktool_run(ktool);

    ktool_free(ktool);

    return 0;
}
