#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <ktool_icons.h>

int32_t ktool_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm ktool!");

    return 0;
}
